support node@<0.8.6

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -276,19 +276,107 @@ install_node() {
   echo
   log install $version
 
-  is_ok $url || abort "invalid version $version"
+  # is_ok $url || abort "invalid version $version"
 
-  log mkdir $dir
-  mkdir -p $dir
-  cd $dir
+  if is_ok $url; then
 
-  log fetch $url
-  curl -L# $url | tar -zx --strip 1
-  erase_line
+    log mkdir $dir
+    mkdir -p $dir
+    cd $dir
 
-  activate $version
-  log installed $(node --version)
-  echo
+    log fetch $url
+    curl -L# $url | tar -zx --strip 1
+    erase_line
+
+    activate $version
+    log installed $(node --version)
+    echo
+
+  else
+
+    install_node_pre086 $version
+
+  fi
+}
+
+#
+# Install node <version<0.8.6> [config ...]
+#
+
+install_node_pre086() {
+  local version=$1; shift
+  local config=$@
+  check_current_version
+
+  # remove "v"
+  version=${version#v}
+
+  # activate
+  local dir=$VERSIONS_DIR/$version
+  if test -d $dir; then
+    # TODO: refactor, this is lame
+    cd $dir \
+      && mkdir -p $N_PREFIX/lib/node \
+      && cp -fr $dir/include/node $N_PREFIX/include \
+      && cp -f $dir/bin/* $N_PREFIX/bin \
+      && cp -fr $dir/lib/node/* $N_PREFIX/lib/node/
+  # install
+  else
+    local tarball="node-v$version.tar.gz"
+    local url="http://nodejs.org/dist/$tarball"
+
+    # >= 0.5.x
+    local minor=$(echo $version | cut -d '.' -f 2)
+    test $minor -ge "5" && url="http://nodejs.org/dist/v$version/$tarball"
+
+    install_tarball_pre086 $version $url $config
+  fi
+}
+
+#
+# Install node <version> <tarball> [config ...]
+#
+
+install_tarball_pre086() {
+  local version=$1
+  local url=$2; shift 2
+  local config=$@
+
+  # remove "v"
+  version=${version#v}
+
+  local dir=$VERSIONS_DIR/$version
+  local tarball="node-v$version.tar.gz"
+  local logpath="/tmp/n.log"
+
+  # create build directory
+  mkdir -p $N_PREFIX/n/node-v$version
+
+  # fetch and unpack
+  cd $N_PREFIX/n/node-v$version \
+    && $GET $url | tar xz --strip-components=1 > $logpath 2>&1
+
+  # see if things are alright
+  if test $? -gt 0; then
+    rm $tarball
+    echo "\033[31mError: installation failed\033[0m"
+    echo "  node version $version does not exist,"
+    echo "  n failed to fetch the tarball,"
+    echo "  or tar failed. Try a different"
+    echo "  version or view $logpath to view"
+    echo "  error details."
+    exit 1
+  fi
+
+  cd "$N_PREFIX/n/node-v$version" \
+    && ./configure --prefix $VERSIONS_DIR/$version $config\
+    && JOBS=4 make install \
+    && cd .. \
+    && cleanup $version \
+    && mkdir -p $dir \
+    && echo $config > "$dir/.config" \
+    && n $version \
+    && ln -s "$N_PREFIX/n/versions/$version" "$N_PREFIX/n/current"
 }
 
 #
